### ISSUE TITLE
lab2 замечания 1

### ISSUE THREAD

**Issue by Andrewbooq** [meridianblade99999/PP#1]
1 добавить использование std::move, get_id(). Найти как можно сконвертировать get_id() в int и использовать значение в вычислениях. Для этого нужно переделать std::bind - передавать вторым параметром не int, а std::placeholders, тогда можно будет в ThreadPool::run() вызов сделать f(threadID);
2 В деструкторе queueCondition.notify_all() не работает как ожидается, нужно wait поправить.
3 threads[i].join() Нельзя звать просто так, нужно убедиться что поток еще живой.
4 В main - this_thread::sleep_for(chrono::milliseconds(100000)) это зачем? Нужно решение получше. Например добавить метод в ThreadPool который возращает размер очереди и просто крутиться в цикле, пока очередь не пустая. Или что-то своё придумать, как распознать, что мы еще не закончили. И, кстати, можно использовать chrono::seconds, чтобы в нолях не путаться.
5 typedef это Си стиль, в плюсах это делается так using userCallBack = std::function<void()>. Идея хорошая.
6 В конструкторе this->shutdown выглядит громоздко. this-> зачем?
7 А вот здесь лучше this вместо & : wait(lock, [&]() {return !queue.empty();}); & - передать всё, хоть и по ссылке, слишком мощьно

Примеры списков захвата для лямбда-выражений
    [] – ничего не захватывает. Нельзя использовать локальные переменные внешней области видимости внутри лямбда-выражения. Можно использовать только параметры.
    [=] – захватывает локальные объекты в области видимости по значению. Можно использовать локальные переменные и параметры, но не изменять.
    [&]  – захватывает локальные объекты в области видимости по ссылкам. Можно изменять локальные переменные и параметры, как в примере выше.
    [this] – захватить this указатель по значению.
    [a, &b] – захватить объекты a по значению, b по ссылке.

Для начала хватит. Когда Закончите, напишите здесь комментарий, я увижу уведомление

**Comment by meridianblade99999** [comment]
Здравствуйте, когда?

Пт, 8 нояб. 2024 г. в 19:02, Andrew ***@***.***>:

**Comment by Andrewbooq** [comment]
В этом issue описаны замечания, я написал в тот же день.
Или я не понял вопрос. Что когда?

**Comment by meridianblade99999** [comment]
Здравствуйте, исправил

**Comment by Andrewbooq** [comment]
А почему int getCurrentThreadId(); вне класса?

**Comment by meridianblade99999** [comment]
Перенес

**Comment by Andrewbooq** [comment]
В остальном всё хорошо

1 Давайте сделаем цикл  `for (int i = 0; i < 10; i++) {` из main не с магическим числом 10, а в два раза больше чем int threadCount (threadCount перенести в мемберы класса и дописать на него геттер, типа getThreadCount() ).

2 Добавляйте какую-нибудь математику (свою, не надо копипастить у других, копипастить можно только у гугла) в void f(int a). Математика должна считаться долго, чтобы потоки успели поработать одновременно. Секунд 10-15-30-...
Математика должна использовать ThreadID. Когда все рассчеты закончены нужет способ сообщить пользователю. Либо засинхронизировать запись в файл результатов, либо в консоль вывести. Должно быть понятно тому кто запускает, что все действия закончились и где найти результат, и что это за результат. Т.е. не просто программа отработала и закрылась. Можно добавить (не обязательно) обработку пользовательского ввода (дополнения к математической части - что считаем, ввод имени файла для сохранения результата, еще что-то свое...). В общем, проявите немного фантазии, приложение должно иметь законченный вид. Мы его еще будем использовать и переделывать в другой лабе.
Возможно это поможет придумать, какую математику использовать:
когда Вы передаете указатель `threadPool.addTask(a);`, то можно вторым и следующими параметрами передавать значения (границы массива, еще что-то), а в очереди `queue<func> queue;` хранить не просто казатели, а структуры (указатель + параметры), и при вызове их отдавать в `void f(int threadId, int begin, int end...)`.

3 Когда все заработает под Windows надо сделать Makefile и собрать приложение под Linux (Ubuntu + VM VirtualBox вполне подойдет).

**Comment by meridianblade99999** [comment]
Сделал

**Comment by Andrewbooq** [comment]
1 Исправить несоответствие типов, компилятор даже ругается
а) std::thread::hardware_concurrency() какой тип возвращает? какой тип везде нужен, где мы используем это значение?
б) threads.size() какой тип возвращает?
в) посмотреть соответствие всех типов в проекте.
```
marchukov/PP/ThreadPool$ mv make.txt Makefile
marchukov/PP/ThreadPool$ make
g++ -c -Wall Main.cpp -o Main.o
g++ -c -Wall ThreadPool.cpp -o ThreadPool.o
ThreadPool.cpp: In destructor ‘ThreadPool::~ThreadPool()’:
ThreadPool.cpp:23:27: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::thread>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
   23 |         for (int i = 0; i < threads.size(); i++)
      |                         ~~^~~~~~~~~~~~~~~~
g++  Main.o ThreadPool.o -o ThreadPool
```
В остальном всё хорошо. Делайте исправление и в чт можно сдавать.

**Comment by meridianblade99999** [comment]
Сделал WindowsThreadPool с использованием windows.h

**Comment by Andrewbooq** [comment]
Не стоит WindowsThreadPool код в 3 лабу лепить. 3 еще не сдана. В Гитхабе по 3 не всё залито, я его в целом видел, порядок должен быть. 
Можно сделать отдельной папкой (по аналогии с PP0) или отдельным бранчем.

**Comment by Andrewbooq** [comment]
По реализации на WinAPI в целом всё правильно, годиться
Нужно же проверять std::thread::hardware_concurrency(), что возвращает не 0? На каждой лабе это говорю.
Нужно проверять передаваемый указатель в run.
Если нулевой указатель это нормальная ситуация, то делаем if (!pointer) return;
Если нулевой указатель не корректная ситуация (как у нас), то assert(nullptr!=pointer)

**Comment by meridianblade99999** [comment]
Здравствуйте, залил 2 и 3 лабы

**Comment by Andrewbooq** [comment]
Смотрю бранч `remotes/origin/lab2`, этих исправлений всё еще нет
1 Исправить несоответствие типов, компилятор даже ругается
а) std::thread::hardware_concurrency() какой тип возвращает? какой тип везде нужен, где мы используем это значение?
б) threads.size() какой тип возвращает?
в) посмотреть соответствие всех типов в проекте.

**Comment by Andrewbooq** [comment]
![image](https://github.com/user-attachments/assets/12a6e98a-acef-46b3-a7fd-dd44db72b79a)

**Comment by meridianblade99999** [comment]
а) беззнаковый
б) тоже беззнаковый
Не ту версию в ветку вынес, исправил

**Comment by Andrewbooq** [comment]
Я бы еще std::this_thread::get_id() сделал unsigned int. Ну допустим, пусть будет так.
